# name: mlops

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   ci-cd:
#     runs-on: ubuntu-latest #macos-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

#     # - name: Lint code with flake8
#     #   run: |
#     #     pip install flake8
#     #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

#     - name: Run tests
#       run: |
#         if [ -f test.py ]; then python test.py; else echo "No tests found."; fi

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2

#     - name: Log in to DockerHub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Build and push Docker image
#       uses: docker/build-push-action@v5
#       with:
#         context: .
#         push: true
#         tags: lienpham04/mlops:latest, lienpham04/mlops:${{ github.sha }}
#         cache-from: type=registry,ref=lienpham04/mlops:cache
#         cache-to: type=inline

#     - name: Deploy to DockerHub
#       uses: appleboy/ssh-action@v1.0.0
#       with:
#         host: ${{ secrets.SERVER_IP }}
#         username: ${{ secrets.SERVER_USER }}
#         key: ${{ secrets.SERVER_SSH_KEY }}
#         script: |
#           docker pull lienpham04/mlops:latest
#           docker stop mlops-container || true
#           docker rm mlops-container || true
#           docker run -d --name mlops-container -p 8501:8501 lienpham04/mlops:latest










name: MLops

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: lienpham04/mlops:latest
