
name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/naa:latest .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/naa:latest

    # - name: Deploy to remote server via SSH
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_IP }}
    #     username: ${{ secrets.SERVER_USER }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     script: |
    #       cd ~/naa
    #       git pull origin main
    #       docker-compose down
    #       docker-compose pull
    #       docker-compose up -d --build


# Push to Docker hub (*Note: DOCKER_USERNAME and DOCKER_PASSWORD are in GitHub Secrets)
    # - name: Log in to Docker Hub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # - name: Push to Docker Hub
    #   run: docker push lienpham04/naa:latest


