name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker-compose services
      run: |
        docker-compose build

    - name: Check Streamlit container builds
      run: |
        docker-compose run --rm streamlit-app echo "✅ Streamlit container OK"
